"""Post attachments

Revision ID: 005b57514cdd
Revises: c4c4815ef381
Create Date: 2019-10-19 16:37:58.582356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005b57514cdd'
down_revision = 'c4c4815ef381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'uploads', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_column('uploads', 'post_id')
    # ### end Alembic commands ###
