"""Post timestamp

Revision ID: 21c803987f85
Revises: 611ba18e9d5f
Create Date: 2019-09-09 16:36:19.215733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c803987f85'
down_revision = '611ba18e9d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###
