"""Post metadata

Revision ID: 2a984c4f994b
Revises: 0b369a32394d
Create Date: 2019-10-25 22:18:24.637028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a984c4f994b'
down_revision = '0b369a32394d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_meta')
    # ### end Alembic commands ###
