"""Tag display name

Revision ID: 31d393ed60c2
Revises: 2a984c4f994b
Create Date: 2019-10-26 21:43:10.170790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d393ed60c2'
down_revision = '2a984c4f994b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'display_name')
    # ### end Alembic commands ###
