"""Login stats

Revision ID: 42dea730ebe1
Revises: 5fd43144a0ca
Create Date: 2019-08-27 12:11:42.319987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42dea730ebe1'
down_revision = '5fd43144a0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logins', sa.Column('last_action', sa.DateTime(), nullable=True))
    op.alter_column('logins', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logins', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('logins', 'last_action')
    # ### end Alembic commands ###
