"""Last login time field

Revision ID: 5fd43144a0ca
Revises: eca5db5f5472
Create Date: 2019-08-25 12:56:11.545827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd43144a0ca'
down_revision = 'eca5db5f5472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logins', sa.Column('last_login', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logins', 'last_login')
    # ### end Alembic commands ###
