"""Posts table

Revision ID: 611ba18e9d5f
Revises: c0e517a11b26
Create Date: 2019-09-06 18:36:13.431935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611ba18e9d5f'
down_revision = 'c0e517a11b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('flake', sa.BigInteger(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
