"""User uri column

Revision ID: 8f220f5669f0
Revises: 31d393ed60c2
Create Date: 2019-10-29 02:25:02.230184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f220f5669f0'
down_revision = '31d393ed60c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uri', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'uri')
    # ### end Alembic commands ###
