"""Remove mimetype

Revision ID: 99eb78392b4e
Revises: 005b57514cdd
Create Date: 2019-10-19 16:51:00.827121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99eb78392b4e'
down_revision = '005b57514cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'mimetype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('mimetype', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
