"""User settings

Revision ID: c908a775debe
Revises: 8f220f5669f0
Create Date: 2019-11-02 13:44:20.532475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c908a775debe'
down_revision = '8f220f5669f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logins', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logins', 'settings')
    # ### end Alembic commands ###
